# Testing a simple Decision Tree Regressor on the NC data

Trying to predict **leaf area index, high vegetation** (lai_hv)

In [7]:
import os
import sys
import cdsapi
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import netCDF4 as nc
import numpy as np
import xarray as xa
import pandas as pd
import glob

module_path = os.path.abspath(os.path.join('./get_dataset'))
if module_path not in sys.path:
    sys.path.append(module_path)

import dataset_api as api

In [39]:
lat = [44.4, 44.8]
lon = [3.6, 4.5]
area_france = [lat[1], lon[0], lat[0], lon[1]]

folder = '.'
path = folder + '/ERA5_land.nc'
#api.get_era5_land(path)

In [40]:
with xa.open_mfdataset(path) as ds:
    df_cds = ds.to_dataframe() 

### Averaging on time values
df_cds = df_cds.groupby(['latitude', 'longitude']).mean()
print(df_cds.shape)
df_cds.head()

(50, 22)

                            d2m         t2m       fal    lai_hv    lai_lv  \
latitude  longitude
44.400002 3.6        277.496429  282.621643  0.164273  2.267111  2.342778
          3.7        276.819000  282.129486  0.159346  2.166003  0.201470
          3.8        276.792114  282.434509  0.148068  2.275795  1.400902
          3.9        277.342590  283.359924  0.133727  2.355388  2.371155
          4.0        278.408569  284.801941  0.118431  2.329728  2.962471

                          src         skt        stl1        stl2        stl3  \
latitude  longitude
44.400002 3.6        0.000099  282.336792  282.788910  282.752533  282.685852
          3.7        0.000086  281.975800  282.352112  282.322357  282.262207
          3.8        0.000087  282.317017  282.718201  282.685242  282.616516
          3.9        0.000088  283.230286  283.653351  283.614807  283.530273
          4.0        0.000087  284.625580  285.081451  285.035248  284.925598

                     ...         ssr        str            sp        ssrd  \
latitude  longitude  ...
44.400002 3.6        ...  12423977.0 -5355694.0  90546.031250  14748765.0
          3.7        ...  12497523.0 -5225019.0  88918.429688  14803388.0
          3.8        ...  12682524.0 -5258744.5  89169.421875  14865689.0
          3.9        ...  12922853.0 -5481798.5  90912.835938  14932132.0
          4.0        ...  13186053.0 -5891225.5  93966.617188  15000342.0

                           strd        tp     swvl1     swvl2     swvl3  \
latitude  longitude
44.400002 3.6        25769978.0  0.003235  0.337979  0.340152  0.339810
          3.7        25742658.0  0.003461  0.349543  0.348219  0.340912
          3.8        25856780.0  0.003594  0.336781  0.334866  0.327907
          3.9        26032944.0  0.003697  0.328119  0.326292  0.321483
          4.0        26236940.0  0.003784  0.316781  0.315108  0.313654

                        swvl4
latitude  longitude
44.400002 3.6        0.383521
          3.7        0.386739
          3.8        0.376442
          3.9        0.373128
          4.0        0.368169

[5 rows x 22 columns]

## Land Dataset

In [49]:
df_land = pd.read_csv('./france_land.csv')
df_land = df_land.drop(columns=['Unnamed: 0'])

df_land = df_land.loc[(df_land['latitude'] >= lat[0]) & (df_land['latitude'] <= lat[1]) 
                        & (df_land['longitude'] >= lon[0]) & (df_land['longitude'] <= lon[1])]

df_land = df_land.set_index(['latitude', 'longitude'])
df_land = df_land.drop(columns=['DMP300-RT0-QFLAG', 'GDMP300-RT0-QFLAG', 'FAPAR300-RT0-NOBS', 
                                'FAPAR300-RT0-LENGTH-AFTER','FAPAR300-RT0-QFLAG', 'FAPAR300-RT0-RMSE',
                               'FAPAR300-RT0-LENGTH-BEFORE', 'FCOVER300-RT0-QFLAG','FCOVER300-RT0-LENGTH-AFTER',
                                'FCOVER300-RT0-NOBS', 'FCOVER300-RT0-LENGTH-BEFORE','FCOVER300-RT0-RMSE', 
                               'LAI300-RT0-LENGTH-BEFORE','LAI300-RT0-LENGTH-AFTER', 'LAI300-RT0-NOBS',
                                'LAI300-RT0-RMSE', 'LAI300-RT0-QFLAG','SWI1km-QFLAG-015', 'SWI1km-QFLAG-020',
                                'SWI1km-QFLAG-060', 'SWI1km-QFLAG-010', 'SWI1km-SSF',
                                'SWI1km-QFLAG-005', 'SWI1km-QFLAG-100', 'SWI1km-QFLAG-040',
                                'SWI1km-QFLAG-002', 'SSM1km-ssm-noise', 'LST-Q-FLAGS', 
                                'LST-PERCENT-PROC-PIXELS', 'LST-ERRORBAR-LST','LST-TIME-DELTA',
                               'ALDH-AL-DH-QFLAG', 'ALDH-NMOD', 'ALDH-LMK', 'ALDH-AL-DH-BB-ERR',
                                'ALDH-AL-DH-VI-ERR', 'ALDH-AL-DH-NI-ERR', 'ALBH-LMK',
                                'ALBH-NMOD', 'ALBH-AL-BH-QFLAG','ALBH-AL-BH-BB-ERR', 
                                'ALBH-AL-BH-VI-ERR', 'ALBH-AL-BH-NI-ERR', 
                               'TOCR-TOCR-QFLAG', 'TOCR-NMOD','TOCR-REF-NOR-SWIR-ERR', 
                                'TOCR-REF-NOR-RED-ERR','TOCR-REF-NOR-BLUE-ERR', 'TOCR-SZN',
                                'TOCR-REF-NOR-NIR-ERR', 'BA300-FDOB-DEKAD', 'BA300-BA-DEKAD',
                                'BA300-FDOB-SEASON', 'BA300-CP-DEKAD'])
df_land.head()

Empty DataFrame
Columns: [NDVI, ALBH-AL-BH-NI, ALBH-AL-BH-VI, ALBH-AL-BH-BB, ALDH-AL-DH-BB, ALDH-AL-DH-VI, ALDH-AL-DH-NI, DMP300-RT0-DMP, FAPAR300-RT0-FAPAR, FCOVER300-RT0-FCOVER, GDMP300-RT0-GDMP, LST-LST, LAI300-RT0-LAI, SSM1km-ssm, SWI1km-SWI-002, SWI1km-SWI-100, SWI1km-SWI-040, SWI1km-SWI-005, SWI1km-SWI-010, SWI1km-SWI-060, SWI1km-SWI-015, SWI1km-SWI-020, TOCR-REF-NOR-BLUE, TOCR-REF-NOR-NIR, TOCR-REF-NOR-SWIR, TOCR-REF-NOR-RED, VCI_x, VCI_y]
Index: []

[0 rows x 28 columns]

### Handling null values

By counting the null values for each column we can see that some of them are null in almost all of our dataset.

In [6]:
df_land_null_cols = df_land.isnull().sum()
print("Unique number of null values per columns: ", df_land_null_cols.unique())
print("Number of columns with null count >= 3000: ", len(df_land_null_cols[df_land_null_cols >= 15000].index))

null_cols = df_land_null_cols[df_land_null_cols >= 3000].index

df_land = df_land.drop(columns=null_cols)

Unique number of null values per columns:  [   0 3542 3431]
Number of columns with null count >= 3000:  0

As for the columns, some row have most of their values null

In [7]:
df_land_null_rows = df_land.isnull().sum(axis=1)
print("Unique number of null values per rows: ", df_land_null_rows.unique())
print("Number of rows with null count >= 60: ", df_land_null_rows[df_land_null_rows >= 60].count())
null_rows = df_land_null_rows[df_land_null_rows >= 60].index
df_land = df_land.drop(null_rows)

Unique number of null values per rows:  [0]
Number of rows with null count >= 60:  0

In [8]:
df_land

,,NDVI,ALBH-AL-BH-NI,ALBH-LMK,ALBH-AL-BH-VI,ALBH-NMOD,ALBH-AL-BH-BB,ALBH-AL-BH-QFLAG,ALBH-AL-BH-BB-ERR,ALBH-AL-BH-VI-ERR,ALBH-AL-BH-NI-ERR,...,TOCR-REF-NOR-SWIR-ERR,TOCR-REF-NOR-RED-ERR,TOCR-REF-NOR-BLUE,TOCR-REF-NOR-BLUE-ERR,TOCR-REF-NOR-NIR,TOCR-SZN,TOCR-REF-NOR-NIR-ERR,TOCR-REF-NOR-SWIR,TOCR-REF-NOR-RED,VCI_y
latitude,longitude,,,,,,,,,,,,,,,,,,,,,
44.40,3.6,6.211765,1208.0,9.0,965.0,213.0,2276.0,3527.0,4.0,845.0,470.0,...,4.0,59.0,624.0,187.0,575.0,105.0,27.0,16.0,8.0,182.0
44.41,3.6,5.976471,1221.0,5.5,973.5,214.5,1995.0,3118.5,2.0,861.5,353.0,...,4.0,38.5,578.0,156.5,557.0,105.0,25.5,25.5,7.0,203.5
44.42,3.6,5.400000,1232.0,4.0,981.0,202.0,1959.0,3059.0,0.0,881.0,359.0,...,0.0,39.0,542.0,150.0,522.0,105.0,26.0,6.0,8.0,202.0
44.43,3.6,5.682353,1273.0,3.0,1011.0,204.0,1407.0,2185.0,0.0,955.0,285.0,...,0.0,12.0,322.0,80.0,391.0,105.0,22.0,21.0,3.0,217.0
44.44,3.6,6.429412,1268.0,3.0,1007.0,204.0,1415.0,2177.0,0.0,947.0,302.0,...,0.0,9.0,292.0,75.0,398.0,105.0,23.0,9.0,3.0,182.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44.76,4.5,6.638235,1209.5,4.0,967.5,204.0,1686.5,2622.5,0.0,853.0,337.0,...,2.0,13.0,285.0,55.0,458.0,105.0,25.0,9.0,3.0,250.0
44.77,4.5,6.357353,1217.0,4.0,971.5,202.0,1739.5,2675.0,0.0,861.5,382.0,...,4.0,18.5,367.5,66.0,499.0,105.0,30.5,13.0,3.0,250.0
44.78,4.5,6.226471,1219.0,4.0,973.0,202.0,1855.0,2860.5,0.0,863.0,403.5,...,2.0,22.5,440.5,88.0,605.5,105.0,33.0,16.0,2.5,154.0
44.79,4.5,5.955882,1211.5,4.5,968.0,202.0,1815.0,2802.5,0.0,855.0,399.5,...,2.0,21.5,364.0,82.5,501.5,105.0,28.0,7.0,4.5,152.0
44.80,4.5,6.337500,1217.5,4.0,972.0,202.0,1788.5,2743.0,0.0,863.0,406.0,...,2.0,18.0,375.5,74.0,538.0,105.0,31.0,15.0,3.0,178.0

## Merge of Climate and Land dataset

In [33]:
# The combined index is composed as (latitude*100)(longitude*100)
# x*yyyyy 
# where x* is a variable length number representing latitude*100
# and yyyyy is a 5 digits longitude*100 with zero padding

combine_index = (lambda x: int(str(int(x[0]*100))+str(int(x[1]*100)).zfill(5)))
df1 = df_cds.copy()
df2 = df_land.copy()

df1.index = df1.index.map(combine_index)
df1.index.name = "latitude-longitude"
df2.index = df2.index.map(combine_index)
df2.index.name = "latitude-longitude"

df = pd.merge_asof(df2.sort_values(['latitude-longitude']), df1, on='latitude-longitude', allow_exact_matches=False)

## Occurrences

In [13]:
df_efa = pd.read_csv("./EEA_latLon_france.csv", index_col=['latitude', 'longitude'])
df_efa = df_efa.drop(columns=['Unnamed: 0'])
df_efa

                    endemic_percentage
latitude longitude
44.92    3.43                 0.433788
         3.44                 0.431838
         3.45                 0.280900
         3.47                 0.538315
         3.48                 0.435600
...                                ...
44.36    4.60                 0.236203
         4.61                 0.161611
         4.62                 0.031687
44.37    4.64                 0.026899
         4.65                 0.054761

[6510 rows x 1 columns]

In [72]:
# Concatenate all data into one DataFrame
df3 = df_efa.copy()

df3.index = df3.index.map(combine_index)
df3.index.name = "latitude-longitude"

df = pd.merge_asof(df.sort_values(['latitude-longitude']), df3.sort_values(['latitude-longitude']), on='latitude-longitude', allow_exact_matches=False)

,latitude-longitude,NDVI,ALBH-AL-BH-NI,ALBH-LMK,ALBH-AL-BH-VI,ALBH-NMOD,ALBH-AL-BH-BB,ALBH-AL-BH-QFLAG,ALBH-AL-BH-BB-ERR,ALBH-AL-BH-VI-ERR,...,ssrd,strd,tp,swvl1,swvl2,swvl3,swvl4,endemic_percentage_x,endemic_percentage_y,endemic_percentage
0,444000360,6.211765,1208.0,9.0,965.0,213.0,2276.0,3527.0,4.0,845.0,...,14748765.0,25769978.0,0.003235,0.337979,0.340152,0.339810,0.383521,0.058482,0.058482,0.058482
1,444000361,5.905882,1208.0,8.0,965.0,216.0,2249.0,3492.0,0.0,845.0,...,14748765.0,25769978.0,0.003235,0.337979,0.340152,0.339810,0.383521,0.022500,0.022500,0.022500
2,444000362,5.364706,1207.0,8.0,965.0,216.0,2341.0,3589.0,4.0,845.0,...,14748765.0,25769978.0,0.003235,0.337979,0.340152,0.339810,0.383521,0.022500,0.022500,0.022500
3,444000363,8.061765,1215.0,6.0,970.0,216.0,2243.0,3446.0,4.0,856.0,...,14748765.0,25769978.0,0.003235,0.337979,0.340152,0.339810,0.383521,0.022500,0.022500,0.022500
4,444000364,8.039216,1238.0,5.0,985.0,213.0,2150.0,3323.0,4.0,887.0,...,14748765.0,25769978.0,0.003235,0.337979,0.340152,0.339810,0.383521,0.022500,0.022500,0.022500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3726,448000446,6.214706,1195.0,7.0,958.0,202.0,1984.0,3174.0,0.0,837.0,...,14911973.0,26671668.0,0.003713,0.334163,0.334872,0.330649,0.373588,0.159947,0.159947,0.159947
3727,448000447,7.054412,1194.0,7.0,958.0,202.0,1769.0,2813.0,4.0,838.0,...,14911973.0,26671668.0,0.003713,0.334163,0.334872,0.330649,0.373588,0.062683,0.062683,0.062683
3728,448000448,6.297059,1197.0,6.0,960.0,202.0,1860.0,2962.0,4.0,838.0,...,14911973.0,26671668.0,0.003713,0.334163,0.334872,0.330649,0.373588,0.054025,0.054025,0.054025
3729,448000449,6.232353,1201.0,6.0,962.0,202.0,2114.0,3358.0,4.0,841.0,...,14911973.0,26671668.0,0.003713,0.334163,0.334872,0.330649,0.373588,0.042361,0.042361,0.042361
3730,448000450,6.337500,1217.5,4.0,972.0,202.0,1788.5,2743.0,0.0,863.0,...,14911973.0,26671668.0,0.003713,0.334163,0.334872,0.330649,0.373588,0.286916,0.286916,0.286916

## Running basic ml models to test dataset

In [106]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

regressor_index = 'endemic_percentage'

X = pd.DataFrame(x_scaled)
y = df[regressor_index]
X = df.drop(columns=[regressor_index, 'latitude-longitude'])
X = min_max_scaler.fit_transform(X)

In [119]:
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn import svm

tree_model = DecisionTreeRegressor()
svm_model = svm.SVR()

print(np.mean(cross_val_score(svm_model, X, y, cv=10)))
print(np.mean(cross_val_score(tree_model, X, y, cv=10)))

0.7847907744056088
0.9999316848250299

In [118]:
X[:, 1]

array([0.00041955, 0.00041955, 0.00040402, ..., 0.00024862, 0.00031078,
       0.00056718])